### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/EDMC-Canonn#11]
Still getting some issues with random crashes.

Will need to make sure that there are no tkinter objects being accessed

**Comment by NoFoolLikeOne** [comment]
Been re-working the patrol.py to make sure that we don't call any tkinter stuff during the thread. Looking good so far.

Hopefully I wont need to change the inheritance models for all the modules or change the way the queues work

**Comment by CmdrAdama** [comment]
I’m experiencing this. EDMC just closes with no notice or error

**Comment by NoFoolLikeOne** [comment]
What version is giving you the errors?

**Comment by NoFoolLikeOne** [comment]
I think this is fixed... will leave open for a bit longer

**Comment by NoFoolLikeOne** [comment]
not had any crashes for 3 days. calling time on this issue
