### ISSUE TITLE
[BUG] Duplicate GGAL/GGAW in tourist list

### ISSUE THREAD

**Issue by teptec** [canonn-science/EDMC-Canonn#121]
**What is your commander name**
Teptec

**What version are you running**
6.3.3

**Describe the bug**
Tourist listings for GGAL and GGWL show up more than once

**To Reproduce**
FSS a system

I feel like one entry appears when the body is FSS'd. Then the second when it's DSS'd.
Perhaps also if a system has been previously scanned, just FSS'ing the system is enough to see double.

**Expected behavior**
Each body would show once in the Tourist list.

**Screenshots**
![image](https://user-images.githubusercontent.com/96891024/153738272-7beacd29-6c6c-47b7-9e86-a53cea88a78d.png)

**Log Files**
Nothing interesting in there.

**Additional context**
Note in screen shot one entry has a hyphen and one doesn't.

**Comment by NoFoolLikeOne** [comment]
Fixed in latest develop version
