### ISSUE TITLE
[BUG] False report of Bark Mounds on a body with no biological signals

### ISSUE THREAD

**Issue by teptec** [canonn-science/EDMC-Canonn#122]
**What is your commander name**
Teptec

**What version are you running**
6.3.3

**Describe the bug**
Plugin shows Bark Mounds on a body with no biological signals.

**To Reproduce**
Go to IC 1287 Sector RO-Q b5-1 and check planet B 2

**Expected behavior**
If a biological doesn't exist on a body, the plugin wouldn't show that it does.
Unless of course I'm completely misunderstanding how Bark Mounds work, which is likely because despite much searching I've never seen one.

**Screenshots**
![image](https://user-images.githubusercontent.com/96891024/155493937-2cc7b913-7e60-4dbd-ad3e-ef65a44e3df0.png)

![image](https://user-images.githubusercontent.com/96891024/155493999-ebc85008-5f04-4e42-9602-868a320f0c51.png)

**Log Files**
n/a

**Additional context**
I'm running Odyssey, perhaps this body has Bark Mounds in Horizons??

**Comment by NoFoolLikeOne** [comment]
Bark mounds have been vanishing in Odyssey. We have been trying to campaign to get them back.

https://youtu.be/U6Q5A6RgG7k

**Comment by teptec** [comment]
I saw that video, this and the Bacterium one are hilarious. I've never actually seen a bark mound in game. Maybe I should restart in Horizons :)

**Comment by NoFoolLikeOne** [comment]
Horizons Bark Mounds have been removed,
