### ISSUE TITLE
[BUG] Cactoida Pullulanta - Green price in codex_name_ref.json

### ISSUE THREAD

**Issue by teptec** [canonn-science/EDMC-Canonn#125]
**What is your commander name**
Teptec

**What version are you running**
6.3.3

**Describe the bug**
The price of Cactoida Pullulanta - Green in data/codex_name_ref.json is incorrect.
Price in file is 711500, price paid by Vista Genomics is 222500

**To Reproduce**
Scan Cactoida Pullulanta - Green and sell it.

**Expected behavior**
I expect the price in the data file to match the price paid by Vista Genomics

**Screenshots**

![image](https://user-images.githubusercontent.com/96891024/155869653-2835786c-0e17-4175-aef3-e4ab45ebae86.png)

**Log Files**

**Additional context**

**Comment by NoFoolLikeOne** [comment]
Can you check what was actually present on the body. The game is is mixing up pullulanta green with vermin so it may be related to that

**Comment by teptec** [comment]
Yeah, the game is totally confused. But the amount I received was 222500.

The composition scan:
```
{
	"timestamp": "2022-02-27T02:57:40Z",
	"event": "CodexEntry",
	"EntryID": 2330403,
	"Name": "$Codex_Ent_Cactoid_03_A_Name;",
	"Name_Localised": "Cactoida Vermis - Green",
	"SubCategory": "$Codex_SubCategory_Organic_Structures;",
	"SubCategory_Localised": "Organic structures",
	"Category": "$Codex_Category_Biology;",
	"Category_Localised": "Biological and Geological",
	"Region": "$Codex_RegionName_34;",
	"Region_Localised": "Sanguineous Rim",
	"System": "Outotz BP-I d9-6",
	"SystemAddress": 216887478483,
	"Latitude": 48.321465,
	"Longitude": -98.403214,
	"IsNewEntry": true
}
```

The Genetic sampler analysis:

```
{
	"timestamp": "2022-02-27T03:51:03Z",
	"event": "ScanOrganic",
	"ScanType": "Analyse",
	"Genus": "$Codex_Ent_Cactoid_Genus_Name;",
	"Genus_Localised": "Cactoida",
	"Species": "$Codex_Ent_Cactoid_04_Name;",
	"Species_Localised": "Cactoida Pullulanta",
	"SystemAddress": 216887478483,
	"Body": 10
}
```

**Comment by teptec** [comment]
Also, the system is here:
https://canonn-science.github.io/canonn-signals/index.html?system=216887478483

**Comment by teptec** [comment]
I'm considering logging a bug on the Frontier site. But I'm seriously concerned that they'll b0rk the fix and we'll never see Cactoida Pullulanta - Green ever again.
Perhaps we could collaborate on a bug report to increase the chance of a successful patch?

**Comment by NoFoolLikeOne** [comment]
The problem here is the comp scan and codex don't match on the species.

I match the name on CodexEntry with the species in the scanorganic. I sure I could fix it but the prices are generated dynamically currently on the assumption that they could change

**Comment by NoFoolLikeOne** [comment]
The Journal Was fixed
