### ISSUE TITLE
[BUG] System Target Info doesn't work for targeted systems along a route

### ISSUE THREAD

**Issue by Tsunakami** [canonn-science/EDMC-Canonn#140]
**What is your commander name**
CMDR Tsunakami

**What version are you running**
Version 6.9.0

**Describe the bug**
System Target Info doesn't work for targeted systems along a route.

**To Reproduce**
Plot a route and target a system on it.

**Expected behavior**
Systems along a route should also show target info.

**Screenshots**
Targeting system before plotting route.
![Screenshot (164)](https://user-images.githubusercontent.com/108987228/178109225-18a04e54-e75f-4064-a4ef-841207dae797.png)
After plotting route to system and targeting it again.
![Screenshot (165)](https://user-images.githubusercontent.com/108987228/178109230-b5f17787-d676-4774-8e82-4760801eca44.png)

**Additional context**
This happens to any system along the route, not just the next jump.
Continues to not pull target info even after clearing the route and re-targeting system.
A separate route must be plotted in order to pull info from systems previously targeted as part of a route.
Currently playing in Odyssey.

**Comment by NoFoolLikeOne** [comment]
This is by design currently because of the timing of the target event while jumping. I'll review
When you clear the route does route.json get emptied? If it does then we should expect EDMC to clear the route in the state variable.

**Comment by Tsunakami** [comment]
I was hoping that wouldn't be the case. 
I'll have to check the route.json when I get home. 
If you could tell me the directory for where that should be, I'd appreciate it.

**Comment by Tsunakami** [comment]
NavRoute.json does not get cleared when clearing my route in-game.

**Comment by NoFoolLikeOne** [comment]
Oh that's a pain. I'll raise that in EDCD and will see what they say. 

New version of the plugin allows target along route I was able exclude events mid jump

**Comment by NoFoolLikeOne** [comment]
Fixed
