### ISSUE TITLE
[FEATURE] nearest guardian [weapon|module|ship|ruin|layout|etc]

### ISSUE THREAD

**Issue by danielschill** [canonn-science/EDMC-Canonn#149]
**Is your feature request related to a problem? Please describe.**
There is no easy to to search for the nearest guardian xxx to your current location.

**Describe the solution you'd like**
Add to the nearest command

**Describe alternatives you've considered**
Inara nearest could possibly add but I think cannon has the better list.

**Comment by NoFoolLikeOne** [comment]
If you go into settings and hide all the Patrols Except Guardians then the patrols will show you only guardian sites and you can use the green arrow in the right to skip to the next site. 

![Capture](https://user-images.githubusercontent.com/31373535/192398966-f9f5ba54-237b-45a8-8248-23045ecee976.PNG)
