### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dauthiatull** [canonn-science/EDMC-Canonn#150]
**What is your commander name**
dauthiatull

**What version are you running**
latest

**Describe the bug**
overlay not working

**To Reproduce**

**Expected behavior**
overlay on screen
**Screenshots**

**Log Files**

**Additional context**

[EDMarketConnector-debug.log](https://github.com/canonn-science/EDMC-Canonn/files/9651464/EDMarketConnector-debug.log)

**Comment by Eahlstan** [comment]
Are you running Elite in fullscreen mode?
