### ISSUE TITLE
[BUG] Hyperdictions are not uploading

### ISSUE THREAD

**Issue by KamilPacanek** [canonn-science/EDMC-Canonn#154]
**What is your commander name**
CMDR Asentinn

**What version are you running**
6.9.7

**Describe the bug**
I'm clicking "Click here to scan all your journals for Hyperdictions", label is cleared and nothing happen. Discord alerts channel also is not updated.

**To Reproduce**
![cannon-hyperdictions](https://user-images.githubusercontent.com/20944885/204090360-62ef8715-18ca-4a59-9232-cac391d0306b.gif)

**Expected behavior**
Any message should popup saying what failed or not.

**Screenshots**
-

**Log Files**
[EDMarketConnector-debug.log](https://github.com/canonn-science/EDMC-Canonn/files/10096307/EDMarketConnector-debug.log)

**Additional context**
-

**Comment by NoFoolLikeOne** [comment]
The hyperdictions get stored in the database but there are no alerts unless the locations have never been seen before.

I'll double check when I'm near a computer. But to tell the truth I was planning on removing that button.

**Comment by KamilPacanek** [comment]
Well, it's up to you if you remove it or not. I got hyperdicted today at Swakhu System.
https://www.youtube.com/watch?v=xn_PRhLUnTk

Downloaded the plugin, configured and just wanted to update Canonn database with my data.
