### ISSUE TITLE
`CodexTypes.raw_mats is None` causing plugin error on all systems (as far as I can tell)

### ISSUE THREAD

**Issue by slippycheeze** [canonn-science/EDMC-Canonn#155]
Note: I'm also getting an EXTOOL senddata error at the moment, due to a PHP-side issue on the server, so this *may* be a downstream "can't happen" situation from that.

Exception is here:
https://github.com/canonn-science/EDMC-Canonn/blob/257479979c1595b04b6dc1a1edfa07657f7fe8f9/canonn/codex.py#L2922

Patching it myself with `if CodexTypes.raw_mats is not None and CodexTypes.raw_mats.get(target.lower()):` fixed it for me, and I now get the plethora of status icons for systems.     Checking the code it was obvious that there is only one place that will ever set the field, in `journal_entry_wrap`, and this was an "obviously correct enough for now" fix. :)

I can reproduce the error logs and send them, or supply whatever additional data would be helpful, if you wish.  Probably best to @-me on the cannon science discord (SlippyCheeze#5125) since I'm quite slow to respond to issues here, though I try. :)

**Comment by NoFoolLikeOne** [comment]
Thanks I'll look into it

**Comment by slippycheeze** [comment]
<3  thank you.  LGTM, for what that is worth.  Leaving this open, because I don't know your issue handling policies.
