### ISSUE TITLE
[FEATURE] "canonn dest" on overlay game screen..

### ISSUE THREAD

**Issue by gabolander** [canonn-science/EDMC-Canonn#163]
I would like "canonn dest" bearing indications were visible as overlay (if overlay feature is enable) instead in EDMC window as it is working right now.

It would make users happy above all when they use VR and willing the information on main game screen while driving a ship on the exact location on a planet surface ...

Tnx in advance for your attention, and keep up the excellent work! O7

**Comment by NoFoolLikeOne** [comment]
We used to have that in Extool. I'll see if ai can bring that back
