### ISSUE TITLE
[BUG] Exobio sites list can get too long, leaves bearing indicator unusable

### ISSUE THREAD

**Issue by mehpersonguy0** [canonn-science/EDMC-Canonn#164]
**What is your commander name**
Sync D'Churro

**What version are you running**
Odyssey 4.0 (Live)
EDMC 5.8.1
EDMC-Canonn 7.0.0
Win 10

**Describe the bug**
When using the per-planet exobiology sites list, if there are several forms with over 50-80 locations listed the list becomes absurdly long- can cause issues for those using low-resolution screens, especially with "Billionaire's Boulevard" planets (120+ locations listed per bioform in this case from all the CMDRs listing similar data) and leaves the bearing indicator/portions of the list, and any readout below unreadable.  

**To Reproduce**
Go to any planet listed in a "Billionaire's Boulevard" exobio route [ie HIP 84676, planet 5 b] in-game, then from EDMC-Canonn select the planet-specific exobio list for said planet

**Expected behavior**
The list may or may not lag out/slowly render (depending on hardware- mine took ~20 sec to load for example screenshot) but when loaded, the lower half of the exobio list, bearing indicator, and update button/info readout below are obscured/unusable

**Screenshots**
[screenshot taken on 2560 x 1440 screen, EDMC set to 90% zoom; in-game menu for scale]

![image](https://user-images.githubusercontent.com/108321550/218295373-0ceb1114-1e75-4241-9569-6088c59b047c.png)

**Log Files**
[N/A]

**Additional context**
If possible, being able to resize the window, or limiting the # of locations listed per item may resolve the issue- I wasn't able to resize the window to adjust for that it seemed though, since it self-adjusts for the list size

**Comment by NoFoolLikeOne** [comment]
Wow that is impressive. I'll see what can be done

**Comment by NoFoolLikeOne** [comment]
Ive updated the server side code to bring back 5 poi locations sorted by maximum distance from the others. 

This should ensure a good spread. Its a bit of a compromise because it does mean that you are unlikely to see other locations that are near you.  But making a change in the plugin itself would have been far too much effort.
