### ISSUE TITLE
[BUG] Cannon plugin link to Signal page for a system is a broken link.

### ISSUE THREAD

**Issue by TonyFlury** [canonn-science/EDMC-Canonn#178]
**What is your commander name**
Flury

**What version are you running**
7.1.1

**Describe the bug**
Link to Cannon Challenge page for HIP 115991 gives a broken link : 

The plugin provides a link to "https://tools.canonn.tech/Signals/?system=HIP 115991" (without the quotes), which results in a page not found error.

**To Reproduce**
In the Cannon plugin, get a link to HIP 115991

**Expected behavior**
It should link to "https://tools.canonn.tech/signals/?system=HIP%20115991" which works as expected.

Note that the correct link has a lower case 'S' in "signals", whereas the plugin gives an upper case S.

**Screenshots**
![image](https://user-images.githubusercontent.com/15114356/229651860-5b8f1a02-379a-43a4-8ed3-c3e308662bc7.png)

**Log Files**

**Additional context**

**Comment by TonyFlury** [comment]
Additional :screenshot showing the correct link (lower case s)

![image](https://user-images.githubusercontent.com/15114356/229652052-66a6e635-fcf8-4dbf-99f5-a8d83abe069f.png)

**Comment by NoFoolLikeOne** [comment]
Sorry it too so long. This should now be fixed
