### ISSUE TITLE
[FEATURE] Biological's Clonal Colony Range to next scannable item's text.

### ISSUE THREAD

**Issue by Jessebob42** [canonn-science/EDMC-Canonn#184]
Description -  Put the Clonal Colony Range with the biological's text.  Just so we know how far to travel for the next viable scan.
![Biologicals](https://github.com/canonn-science/EDMC-Canonn/assets/60488309/28c266b1-c02b-4c97-bb69-f569d8c6c69c)

**Comment by NoFoolLikeOne** [comment]
Thanks for the table. That is really quite useful. 

I think what I might consider is showing a range indicator when you scan something and then hide it when you are further than your last scan

**Comment by NoFoolLikeOne** [comment]
Done.
