### ISSUE TITLE
[BUG] Number of system planets not updating.

### ISSUE THREAD

**Issue by OPlurker1005** [canonn-science/EDMC-Canonn#186]
**What is your commander name**

oplurker1005

**What version are you running**

7.3.1

**Describe the bug**

I jumped into a partially scanned system (Eor Aihm BL-P c5-0) and fully FSS scanned all 15 planets in the system.  The number of planets listed only goes up to 14/15 and no matter what I do the plug-in does not complete. I have rescanned the system with the FSS; jumped out and back into the system and rescanned; logged out to the menu, back in and scanned; exited the game, back in rescanned; exited the game, closed EDMC ran EDD rescanned; exited the game, restarted EDMC and rescanned, but it still will not update.

**To Reproduce**

Try scanning a partially scanned systems. I did run into this before, but it updated the plug-in after I exited the game, closed EDMC, ran EDD, restarted EDMC and restarted the game, but I can not reproduce the fix.

**Expected behavior**

To complete the listed number of planets in the system codex after all planets are scanned.

**Screenshots**
![image](https://github.com/canonn-science/EDMC-Canonn/assets/18335183/d3cd1573-30c4-4759-8153-0a87649e019f)

**Log Files**
[EDMarketConnector-debug.log](https://github.com/canonn-science/EDMC-Canonn/files/11797040/EDMarketConnector-debug.log)

**Additional context**

**Comment by NoFoolLikeOne** [comment]
Spansh is showing 15 bodies and bodyCount 15 to I would expect that to show the correct numbers. Timestamps on spansh are no more recent than 7:18.. if you try again and it looks correct it could have been a late update as 7:18 is an hour after your other scans at 6am

I'll give it a try when I get a chance and see how it looks now.

**Comment by NoFoolLikeOne** [comment]
Its now showing 15/15 so it may have been down to timing.

**Comment by OPlurker1005** [comment]
OK,thanks for checking. That is kind of what I started to think the more I tested, it being down to the differences in databases updating.
