### ISSUE TITLE
[FEATURE] Soundwork: noise red, use mp3

### ISSUE THREAD

**Issue by Artoria2e5** [canonn-science/EDMC-Canonn#187]
**Is your feature request related to a problem? Please describe.**
There is a bit of noise in the voice recordings. They are also wav, which is making up the majority of the download, when every platform can definitely play mp3.

A very small problem of course, considering everything is quiet and tiny in size compared to the game. The background noise in nag1 is a little more noticeable.

**Describe the solution you'd like**
Do a little denoise. The attached file is what I've done with Audacity noise reduction, settings 48 dB, 6, 0:
* nag1: noise sample from ~10.9 - 11.6s. timespan 0 - 23.330s to not hit the intentional noise at the end. [nag1d.zip](https://github.com/canonn-science/EDMC-Canonn/files/12207416/nag1d.zip)
* prefix: noise sample from ~0.3 - 0.45s. timespan also chosen to not hit intention noise at both ends. [prefixd.zip](https://github.com/canonn-science/EDMC-Canonn/files/12207423/prefixd.zip)

In both zipballs are a 16-bit PCM wav and a LAME mp3 compressed at quality 4. Somehow having 0 band-smoothing is ideal for these files -- the spectrogram ends up eerily clear, but the sound is not borked at all.

**Describe alternatives you've considered**
Not do anything at all. Honestly very acceptable.

**Additional context**
You know the kind of annoying person who windirstats everything? Yeah, that's me pinching pennies. And knowing full well getting new binaries files in will only make the git repo bigger!

**Comment by NoFoolLikeOne** [comment]
I would use mp3 but only have native support for wav in edmc. Unless you know of a way of doing it without installing additional libraries?

**Comment by Artoria2e5** [comment]
Don't comments for mac and win both claim MP3 support in playsound.py? GStreamer almost definitely does mp3.

**Comment by NoFoolLikeOne** [comment]
I wrote the code when EDMC was on Python 2.7 I dont think it was supported then. I'll upload your files and see if it will work

**Comment by NoFoolLikeOne** [comment]
It worked. Will be in the next release
