### ISSUE TITLE
[BUG] Canonn-signals web page look damaged when I check a newly discovered system,

### ISSUE THREAD

**Issue by athulin** [canonn-science/EDMC-Canonn#192]
**What is your commander name**
A. Thulin

**What version are you running**
7.3.2

**Describe the bug**
I discover a new system with EDMC-Canonn plugin active.  It does not show the bodies I see in-game, and also on EDSM. 

 When I check the corresponding web page, entries for barycentres appear.

I include the ED journal lines that mention the target system name.

**To Reproduce**
Not sure if I can reproduce in the same session, as FSS state is sticky.  Getting a new session ... will take a long time.
Target system is NGC 4609 Sector PJ-E c13-0. 

**Expected behavior**
I did not expect to see any web page entries for barycentres.

**Screenshots**
![image1](https://github.com/canonn-science/EDMC-Canonn/assets/53051907/b4aa2645-dd3d-4e46-804d-56682a7cad6b)

![image2](https://github.com/canonn-science/EDMC-Canonn/assets/53051907/f8ba8410-415d-465f-bce8-3d9e8ae3260a)

**Log Files**

EDMarketConnector.log is empty.

Journal lines:
[NGC_4609_Sector_PJ-E_c13-0.zip](https://github.com/canonn-science/EDMC-Canonn/files/13780813/NGC_4609_Sector_PJ-E_c13-0.zip)

**Additional context**
I have seen similar behaviour occasionally, but so far not in a star system I discovered myself at the same time.

**Comment by NoFoolLikeOne** [comment]
That is normal behaviour. All the bodies are minimised if there are no signals on them. 

You can click on the little arrows to expand or collapse them

![image](https://github.com/canonn-science/EDMC-Canonn/assets/31373535/3873d63f-fefc-43e0-9f58-9eaa7bbd785a)
