### ISSUE TITLE
Event excludes ignoring a few

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/EDMC-Canonn#30]
**What version are you running**
Reporting on behalf of other users, but based on reports `EDMC-Canonn.1.9.1`

**Describe the bug**
Shutdown event is in the excludes list but is still being sent

**To Reproduce**
Example: https://api.canonn.tech:2083/reportevents?eventname=Shutdown

**Expected behavior**
Shutdown should not be sent to the CAPI as we don't need to store the data.

**Screenshots**
N/A

** Log Files **
No logs as this is reported from our side

**Additional context**
N/A

**Comment by NoFoolLikeOne** [comment]
Change the code to populate a local exclusions list and then when complete this can be copied to the cls.exclusions and this should prevent other threads from reading the data before it is complete.

**Comment by NoFoolLikeOne** [comment]
Need to update the exclusions spreadsheet

- ShutDown -- listed as Shutdown in the sheet
- Statistics -- contains player stats. We will want our own model for that

**Comment by NoFoolLikeOne** [comment]
I've only seen evidence of typos and missing events so far
