### ISSUE TITLE
Add CAPIv2 Alert to news ticketer

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/EDMC-Canonn#32]
**Is your feature request related to a problem? Please describe.**
Per your request on discord we should include the CAPIv2 alerts in the news ticket: 
https://api.canonn.tech:2083/alerts

Example:
```json
[
    {
        "id": 7,
        "title": "EDMC-Canonn Plugin release",
        "body": "Add some link like https://github.com/canonn-science/EDMC-Canonn/releases/latest\n\nMaybe add a few patch notes.\n\nBlah blah blah some text here.\n\nUpdated alert without image",
        "alertLevel": 3,
        "active": true,
        "tldr": "New release for EDMC-Canonn v2.9.49",
        "alertURL": "https://github.com/canonn-science/EDMC-Canonn/releases/latest",
        "created_at": "2019-03-26T12:26:48.000Z",
        "updated_at": "2019-03-26T12:30:11.000Z",
        "alertImage": false
    }
]
```

**Describe the solution you'd like**
Based on the alert level the alert should show up with a "higher" priority ASAP. This would allow us to push alerts to users ASAP as well.

**Comment by NoFoolLikeOne** [comment]
Tkinter doesn't allow us to have html in the body  but I think would only be showing the title and the alertUrl
