### ISSUE TITLE
[BUG] Resize Loop Returned

### ISSUE THREAD

**Issue by Ewanderer** [canonn-science/EDMC-Canonn#39]
commit 4f58fe4

**Describe the bug**
Sometimes the Plugin is stuck in a Resize Loop for the Patrol or Message Text Field, which makes the whole EDMC stutter, which sometimes causes the whole EDMC to crash silently.

**To Reproduce**
No Idea.

**Expected behavior**
Patrols and Canonn should create a stable window

**Screenshots**

**Log Files**

**Additional context**

**Comment by NoFoolLikeOne** [comment]
Hi. 

Could you let me know if there are any other plugins running.

I did see this happening during testing and put some code on the patrol to stop it resizing if it was recently resized. But only did it for the patrol and not the news.

**Comment by Ewanderer** [comment]
Hi,
I am running ExTool and EDMC-Screenshot.

**Comment by NoFoolLikeOne** [comment]
I wouldn't have thought they would be a problem.

I have make a change but not released it yet.

How frequent is the problem for you?

**Comment by Ewanderer** [comment]
I mean I didn't play as much since the Canonn Plugin was added, but I think roughly once every few hours. Was really bothersome since I had to resync my progress with DWII.

**Comment by NoFoolLikeOne** [comment]
What is your commander name? So I can check version numbers.

**Comment by Ewanderer** [comment]
Okay, thanks. If I will keep you updated if it happens afterwards.
