### ISSUE TITLE
[BUG] plugin does not work if there are non-ASCII characters in the path

### ISSUE THREAD

**Issue by VAKazakov** [canonn-science/EDMC-Canonn#46]
**What is your commander name**

Roman Sharp

**What version are you running**

1.9.7

**Describe the bug**

If there are Cyrillic characters on the way to the plug-in folder, the settings disappear, and the main window looks like this [1]
**To Reproduce**

**Expected behavior**

**Screenshots**

![alt text](https://cdn.discordapp.com/attachments/518418556615000074/564752520774418432/unknown.png "main screen")
**Log Files**

[EDMarketConnector (2).log](https://github.com/canonn-science/EDMC-Canonn/files/3053805/EDMarketConnector.2.log)
**Additional context**

**Comment by NoFoolLikeOne** [comment]
fix waiting deployment
