### ISSUE TITLE
[FEATURE] Add automated TB reporting

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/EDMC-Canonn#50]
Example from Codex Reports:

![image](https://user-images.githubusercontent.com/8593673/56583764-2a8b1f00-658f-11e9-9abc-915210137483.png)

Required API POST Format:

POST `/tbreports`

```
{
  "userType": "pc",
  "reportType": "new",
  "systemName": "string",
  "systemAddress": 0,
  "regionID": 0,
  "coordX": 0,
  "coordY": 0,
  "coordZ": 0,
  "bodyName": "string",
  "latitude": 0,
  "longitude": 0,
  "type": "Journal Name",
  "cmdrName": "string",
  "isBeta": false,
  "clientVersion": "string",
  "reportStatus": "pending"
}
```

**Comment by NoFoolLikeOne** [comment]
Shouldn't this just be a case of adding the entry in the reporttypes model?

**Comment by NoFoolLikeOne** [comment]
tb model might require some changes to make it fit in with the other codex report types.

**Comment by derrickmehaffy** [comment]
Yeah I may need to remove the previous custom types and use the journal ones.

Considering the lack of user involvement I'm not sure our custom defined ones are warranted. There will still be some other data that will need user input so it will have to wait for Athena

**Comment by NoFoolLikeOne** [comment]
You have have them in addition to the journal. I'm going to take a look at recording the frontier id.
But not sure if I want to do that for geosites because you can get up to 50 on one body

**Comment by derrickmehaffy** [comment]
Right now I'm not sure of the mapping between them.

And that's the point for the frontier ID is to identify the site at a glance it will also help us determine if the entire system has been mapped for sites ;)

**Comment by NoFoolLikeOne** [comment]
Shame they wont put the id in the journal. It would eliminate the need for haversine

**Comment by derrickmehaffy** [comment]
Aye it would

**Comment by derrickmehaffy** [comment]
added: https://api.canonn.tech/tbreports
