### ISSUE TITLE
[FEATURE] Automated Guardian Structure reporting

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/EDMC-Canonn#51]
Based on the following Journal log:

```
{ "timestamp":"2018-03-03T16:52:53Z", "event":"ApproachSettlement", "Name":"$Ancient_Tiny_002;", "Name_Localised":"Guardian Structure", "MarketID":2952790784 }
```

We should be able to do automated GS reports (GR still not likely due to missing type)

Pulling System, Body, Latitude, and Longitude from the status.json combined with matching the above with https://api.canonn.tech/gstypes

It should be possible to automatically report GS, note that this entry is not a codex one thus /reporttypes doesn't apply here. It's an actual journal entry

**Comment by NoFoolLikeOne** [comment]
Completed
