### ISSUE TITLE
[FEATURE] Disable BGS Patrol calculations

### ISSUE THREAD

**Issue by Doomy66** [canonn-science/EDMC-Canonn#76]
Now that Canonn System Numberwang is up and running, the Bgs guys have requested that your bgs calculated patrols be disabled. Just use the overrides sheet as current.

This will reduce the number of missions and ensure they are all valuable.

No need to remove the code, you never know when CSN might get hit by a bus, just disable.

**Comment by NoFoolLikeOne** [comment]
Done! That's numberwang!
