### ISSUE TITLE
[BUG] Incorrect progress display in DSS

### ISSUE THREAD

**Issue by CMDR-Cometborne** [canonn-science/EDMC-Canonn#77]
Cometborne

5.20.3

When doing the FSS dance of a system, the count in the plugin is off by one.

Jump into a system that is FSS-able, do the FSS mini-game, compare plugin and in-game display.

Count should be the same

**Screenshots**
![image](https://user-images.githubusercontent.com/25147462/86147566-d7e5b500-baf9-11ea-8db5-a79a09f2d657.png)

**Comment by NoFoolLikeOne** [comment]
The first number should show how many bodies are in EDSM not how many you have scanned. It increments each time you scan because it will be in EDSM shortly after.  

Can you double check that it is working as explained?

**Comment by CMDR-Cometborne** [comment]
Checked, and it is not working like this.  Currently in a new system, transmitting data to EDSM(and EDDN, for that matter).  Display by EDSM and the plugin taken at the same time:

![image](https://user-images.githubusercontent.com/25147462/86281033-2a4bd200-bbdd-11ea-89f9-5619811595ac.png)

EDSM shows two bodies, plugin reports three already.

**Comment by NoFoolLikeOne** [comment]
Thanks. I shall investigate

**Comment by NoFoolLikeOne** [comment]
No re-occurence for me
