### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by IanDLive** [canonn-science/EDMC-Canonn#80]
**What is your commander name**
IanD Live

**What version are you running**
5.21.0

**Describe the bug**
The plugin itself will not load on startup of EDMC.  The previous version of the plugin (5.20.4) runs correctly, displays the information and has its settings tab, but upon upgrade to the latest version, the plugin does not load, for the reason highlighted in the log below.

**To Reproduce**
Loading a fresh copy of the 5.21.0 plugin into EDMC.

**Expected behavior**
A working copy of the plugin.

**Screenshots**
N/A

**Log Files**
E:D Market Connector 3.4.3.0 2020-09-27T05:36:20
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin eddn from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
loading plugin autopath from "C:\Users\wolfc\AppData\Local\EDMarketConnector\plugins\autopath\load.py"
Autopath: PLUGIN STARTED
plugin EDMC-Canonn-5.20.4 disabled
loading plugin EDMC-Canonn-5_21_0 from "C:\Users\wolfc\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-5.21.0\load.py"
EDMC-Canonn: Starting the debug sub-system
Traceback (most recent call last):
  File "plug.pyo", line 193, in load_plugins
  File "plug.pyo", line 94, in __init__
  File "C:\Users\wolfc\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-5.21.0\load.py", line 13, in <module>
  File "C:\Users\wolfc\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-5.21.0\canonn\codex.py", line 915
    debug(f"Merge POI {hud_category} {english_name} {body}")
                                                          ^
SyntaxError: invalid syntax
loading plugin HabZone from "C:\Users\wolfc\AppData\Local\EDMarketConnector\plugins\HabZone\load.py"

**Additional context**
N/A

**Comment by NoFoolLikeOne** [comment]
Hi Ian. It looks like you are running an old version of EDMC that uses an obsolete version of python. You need to upgrade to the latest version
