### ISSUE TITLE
[BUG] Using colons in option name causes a crash on Linux

### ISSUE THREAD

**Issue by sersorrel** [canonn-science/EDMC-Canonn#85]
**What is your commander name**
Ser Sorrel

**What version are you running**
5.23.0, 4118a9c, on Linux

**Describe the bug**
If you launch EDMC, open the settings window but do not click on the EDMC-Canonn tab, then close the settings window and try to relaunch EDMC, it'll crash:

```pytb
Traceback (most recent call last):
  File "/home/ash/src/EDMarketConnector/config.py", line 303, in __init__
    self.config.read_file(h)
  File "/usr/local/lib/python3.7/configparser.py", line 717, in read_file
    self._read(f, source)
  File "/usr/local/lib/python3.7/configparser.py", line 1091, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/ash/.config/EDMarketConnector/EDMarketConnector.ini' [line 67]: option 'canonn' in section 'config' already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./EDMarketConnector.py", line 18, in <module>
    from config import applongname, appname, appversion, appversion_nobuild, config, copyright
  File "/home/ash/src/EDMarketConnector/config.py", line 380, in <module>
    config = Config()
  File "/home/ash/src/EDMarketConnector/config.py", line 305, in __init__
    self.config.add_section(self.SECTION)
  File "/usr/local/lib/python3.7/configparser.py", line 658, in add_section
    raise DuplicateSectionError(section)
configparser.DuplicateSectionError: Section 'config' already exists
```

**To Reproduce**
- Install EDMC-Canonn
- Close and reopen EDMC
- Open the settings window, but don't click on the EDMC-Canonn tab
- Close and reopen EDMC

**Expected behavior**
EDMC-Canonn shouldn't use weird config keys that cause EDMC to crash – calling the value `canonnhidecodex` would work fine, just like `canonndebug`. (EDMC also shouldn't _allow_ plugins to do this, but that's a separate issue)

**Additional context**
Initially, EDMC-Canonn puts these two lines in the config file:
```
canonn = hidecodex = 0
canonndebug = 0
```

When you open and close the EDMC settings window without visiting the EDMC-Canonn tab, it adds this line as well:
```
canonn:hidecodex = 0
```

Removing it fixes the issue. As best I can tell, using a colon in a config key trips up configparser (used by EDMC on Linux to store config) in some way, since it allows both an equals sign and a colon to be used to separate keys from values (i.e. `a = 2` and `a: 2` are treated equivalently).

**Comment by NoFoolLikeOne** [comment]
Thanks, Will take a look

**Comment by NoFoolLikeOne** [comment]
I'm not sure how I will address this as to change it would require copying and saving everyone's config. I might bump this up to EDMC and see what they have to say.

**Comment by GrimmerSchnitter** [comment]
Can confirm this issue.
(Using Debian 10 w/ Python 3.7.3, EDMC 4.1.6)

**Comment by dtruesdale88** [comment]
Still an issue with 4.2.2 using python 3.7 Mint 20.04. I have removed this line canonn = hidecodex = 0 and it puts it back after restart. So I leave this line and then this line get's tagged on at the end of the ini canonn:hidecodex = 0. Which if we don't remove EDMC will not run. Can you not just make a temp work around for this till it can be properly fixed?

**Comment by GrimmerSchnitter** [comment]
@dtruesdale88, you could do a workaround by using a startscript like this:
`  sed -i '/canonn:hidecodex = 0/d' ~/.config/EDMarketConnector/EDMarketConnector.ini ;
  python3 path/to/your/EDMarketConnector.py`
This remove the faulty line using `sed` (if it exists) and starts EDMC afterwards...

**Comment by dtruesdale88** [comment]
@GrimmerSchnitter thank you for that, never thought about doing that. Simple fix to a hopefully temp issue......

**Comment by NoFoolLikeOne** [comment]
Sorry I haven't gotten around to looking at this yet. There is a change to the config package on EDMC so I'll see if I can make the change

**Comment by GrimmerSchnitter** [comment]
Thanks and sorry for my late reaction. I didn't play a lot lately.

I recently upgraded to EDMC 5.0.0 and EDMC-Canonn-6.0.0 and checked for the problem again.
The problem seems to be fixed.
After temporarily removing the fix from my start script, the integrity of the INI-file is no longer affected, whether the Canonn-plugin's config is changed or not.
I understand that EDMC itself made some changes in its code, and you did a good job porting the plugin!

Thanks a lot!

**Comment by NoFoolLikeOne** [comment]
@GrimmerSchnitter I did make some changes but may have missed others. I strongly suspect that the fix was because of the extensive changes the awesome EDMC team made extensive changes to config.py

Thank you for confirming that it is fixed.

**Comment by GrimmerSchnitter** [comment]
@NoFoolLikeOne,

Unfortuneately, the bug reappeared after upgrading the plugin to version 6.0.1.
After fixing the config once using my sed-script, it seemed to vanish, but I'm still watching the situation and let you know.
