### ISSUE TITLE
[BUG] distance calculation is off for challenge systems

### ISSUE THREAD

**Issue by CMDR-Cometborne** [canonn-science/EDMC-Canonn#87]
**What is your commander name**

Lydia of the Void

**What version are you running**

5.23.0

**Describe the bug**

If you are in a challenge system, the distance to the system should be 0.  At least in Trifid Sector DL-Y d157 and Trifid Sector FW-W d1-233, it is not, see screenshot.

**To Reproduce**

Go the sector, look at the plugin

**Expected behavior**

If I am in the system, the distance should be 0.

**Screenshots**

![image](https://user-images.githubusercontent.com/25147462/104124021-b25e2180-534e-11eb-9a66-d9641d167cee.png)

**Log Files**

N/A

**Additional context**

N/A

**Comment by NoFoolLikeOne** [comment]
I've updated that specific one but there are a few that will need updating. Looks like some rounding crept in to some of the data.

**Comment by CMDR-Cometborne** [comment]
Found another one:
![image](https://user-images.githubusercontent.com/25147462/111693310-c0d62700-8830-11eb-812f-1c68713de4a8.png)

**Comment by CMDR-Cometborne** [comment]
And one more
![image](https://user-images.githubusercontent.com/25147462/111846756-c0f52600-8907-11eb-9d85-19c304d0f7ac.png)

**Comment by CMDR-Cometborne** [comment]
And the next one
![image](https://user-images.githubusercontent.com/25147462/113188222-0dbaf400-925a-11eb-9fd9-842a5b288fff.png)

**Comment by NoFoolLikeOne** [comment]
Bit if of a hack but because if differences in precision between databases I have made sure if you are in system that it displays zero and also reduced precision on the display
