### ISSUE TITLE
[FEATURE] Version number and github link

### ISSUE THREAD

**Issue by CMDR-Cometborne** [canonn-science/EDMC-Canonn#89]
**Is your feature request related to a problem? Please describe.**
When submitting a bug report for this plugin, I always need to dig through the plugin folder to find the version number, and then search on github for the correct page.  This creates a hurdle for submitting bug reports, especially if the user is not familiar with github, does not know that bug reports for the plugin can be submitted on github.

**Describe the solution you'd like**
Display both the current version number and a link to the github on the plugin settings page.  Example from EDSM-RSE:
![image](https://user-images.githubusercontent.com/25147462/104837550-9eb63c00-58b5-11eb-8c63-db10088f25f3.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by NoFoolLikeOne** [comment]
Added in 5.24.0
