### ISSUE TITLE
[BUG] Challenge progress report is incomplete

### ISSUE THREAD

**Issue by CMDR-Cometborne** [canonn-science/EDMC-Canonn#95]
When querying your progress using https://us-central1-canonn-api-236217.cloudfunctions.net/get_cmdr_codex?cmdr=<cmdr>, the JSON file reports that 48 types of "Mollusc" are available, but the list of "types_available" terminates in the middle of entry 44:

            "Lindigoticum Capsule Mollusc",
            "Viride"
        ],
        "percentage": 25.0

Your initial analysis was:
"Looks like a bug in the python
ah! Looks like the globe mollusc means that the group_concat has exceed the size limit and its just silently truncated
I'm going to have to modify the code a bit"

**Comment by NoFoolLikeOne** [comment]
I modified the code a bit. It is now showing all molluscs
