### ISSUE TITLE
[BUG] EDMC exiting after a few minutes when canonn plugin installed

### ISSUE THREAD

**Issue by hldswrth** [canonn-science/EDMC-Canonn#99]
**What is your commander name**
Zador

**What version are you running**
5.26.0

**Describe the bug**
EDMC program exits after a few minutes. I restart it and then its gone again a few minutes later.
I've deleted the Canonn plugin from the plugins folder and EDMC does not exit.

**To Reproduce**
Other than installing and running, not sure how to reproduce specifically.  I start EDMC, play the game, and often during FSS (which is the most time consuming activity anyway) EDMC exits.

**Expected behavior**
I don't expect to have to keep restarting EDMC

**Screenshots**
N/A

**Log Files**

Can't see any obvious errors, the last line in the debug log before the startup debug entry is often
`DEBUG - 11880:19592:19592 <plugins>.EDMC-Canonn-5.26.0.canonn.codex.CodexTypes.visualise:1331: Not Allowed event`
Although this does appear many times throughout the log so its not unique to the point where the program appears to exit.
Latest failure has as the last line in the debug log
`DEBUG - 4668.19076:19076 <plugins>.EDMC-Canonn-5.26.0.canonn.codex..CodexTypes.getdata:999: Getting POI data in thread None - system = Dryi Aoc LQ-V A116-0`

**Additional context**
I just updated EDMC to release 5 and I see lots of DEBUG logs for deprecated getint() method, EDMC still exiting when canonn plugin installed and running OK if I remove the plugin.

**Comment by NoFoolLikeOne** [comment]
The intermittent crashes is something that has been a problem for a while. Could you try hiding all the patrols and see if that makes it more stable for you.

Let me know if that helps as I think that may be where the problem is coming from but just need corroborating evidence.

The deprecated warnings are known but not anything to do with this issue and will be cleaned up in the next release.

**Comment by hldswrth** [comment]
OK thanks, I will try hiding all the patrols later today.

**Comment by hldswrth** [comment]
With settings as follows I didn't get any crashes:
![Capture](https://user-images.githubusercontent.com/5747825/118200767-d2f9cd80-b44d-11eb-8ef0-c01aa1ad7306.PNG)

**Comment by NoFoolLikeOne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite patrols to eliminate random crashes.](https://trello.com/c/RpQ9RnTa/4-rewrite-patrols-to-eliminate-random-crashes)

**Comment by NoFoolLikeOne** [comment]
It looks like the patrols themselves aren't the problem but it may be copy to clipboard. 

Since disabling copy to clipboard I've not had any crashes
